106 fractionalcurrent
Northeastern-Electric-Racing/shepherd_bms pull request #127
Opened 2023-02-01 14:23 UTC by dyldonahue

## Issue ticket number and issue description
#106 fractional current

I multiplied pack current by 10 to allow for single decimal precision. I then divided it by 10 for all calcs (that did not care about decimal) to ensure all existing calculations were unaffected. 

Please double check that my manipulation of the value is done correctly and that I didn't miss any instances. where it is used

I also did not: 

divide packCurrent by 10 when broadcasting (idk if we wanna see decimal for this or not)
adjust open cell voltage calc to use this
add this value to charging stuff (not merged in yet)

lmk if any of those should be done here

2023-02-01 23:23 UTC, mccauleyma requested changes
Additional to my comments, you missed the current comparison in Analyzer::calcOpenCellVoltage()

2023-02-02 01:05 UTC, dyldonahue commented on shepherd_bms/src/main.cpp
> +	if((bmsdata->packCurrent)/10 > (int16_t)bmsdata->contDCL && BoostState == BOOST_STANDBY)
contDCL was already casted that way, even though it was already a int16. Will remove if that was never meant to be the case

2023-02-02 01:06 UTC, dyldonahue commented on shepherd_bms/src/main.cpp
> +	if((bmsdata->packCurrent)/10 > (int16_t)bmsdata->contDCL && BoostState == BOOST_STANDBY)
The divide vs multiply by 10 was the debate, but yeah I agree so I will flip for all instances

2023-02-03 00:16 UTC, mccauleyma requested changes
Still missing the open cell voltage calc

2023-02-03 00:23 UTC, mccauleyma approved these changes
:)

2023-02-03 01:01 UTC, nwdepatie approved these changes
Seal of approval(but the other seal)

2023-02-03 01:01 UTC, merged