Implemented charge balance timer.
Northeastern-Electric-Racing/shepherd_bms pull request #145
Opened 2023-02-12 21:09 UTC by wfox5812

## Issue ticket number and issue description

Ticket #  -> Fix X

## Describe your changes

Changes made
-
-
-

2023-02-12 21:23 UTC, wfox5812 commented
Didn't declare the variable for the state of the charge balance timer, needs to be added once the state machine initialization is ready.

2023-02-18 17:04 UTC, nwdepatie requested changes
So this PR is gonna stay in PR land for a hot sec until we get the state initialization functionality implemented, but overall I think it looks good, just a small nitpick. That being said, we do have to test this functionality before merging in on hardware

2023-02-18 17:04 UTC, nwdepatie commented on shepherd_bms/src/main.cpp
> +	if (balanceTimer.isTimerExpired() && balanceTimerState == 0)
nit - either make it a boolean ( ```if (isBalancing)```  ) or enumerate these states ( ``` if (balanceTimerState == NOT_BALANCING)``` ) or something, try and avoid magic numbers where possible

2023-03-01 17:47 UTC, mccauleyma requested changes
The other element to this ticket is once timings are implemented, we want to add to the openCellVoltage that it should not update when balancing and then make the balancing algorithm use open cell voltages, instead of live.

This will allow for a smarter balance as it will account for the internal resistance impact

2023-03-01 17:49 UTC, mccauleyma commented
@dyldonahue I assume it is up to you if you want my request to be a part of this PR/ticket or if it needs its own ticket. But the whole point of adding the timers is to implement the better balancing I mention, so imo they are pretty linked in terms of features, but could be easily split in terms of code

2023-03-01 18:14 UTC, dyldonahue commented
will weigh options, based on timeline may end up just being a quick one session fix that gets done asap so might not matter either way

2023-03-13 21:19 UTC, dyldonahue commented
@wfox5812 forgot to mention last week but if u wanted to add onto this with additions @mccauleyma mentioned in the comment above go for it

2023-04-13 10:39 UTC, closed without merging

2023-04-13 10:40 UTC, nwdepatie commented
Closed as we made an updated PR https://github.com/Northeastern-Electric-Racing/shepherd_bms/pull/177