8 charger handler
Northeastern-Electric-Racing/shepherd_bms pull request #51
Opened 2022-11-25 18:39 UTC by nwdepatie

Ticket done by @dyldonahue, [builds off of this PR](https://github.com/Northeastern-Electric-Racing/NERduino/pull/13) to enable talking to the charger over the second CAN line. This ticket should begin comms, send (and potentially handle) messages to/from the charger, and end comms

2022-11-26 18:21 UTC, dyldonahue commented on shepherd_bms/src/compute.cpp
> +    chargerMsg.cfg.chargerVoltage = voltageToSet * 10;
assuming this was checked already, but just making sure that this EQ results in the same Byte 2 and 3 that was produced in the earlier version

2022-11-26 18:23 UTC, dyldonahue approved these changes

2022-12-14 02:08 UTC, mccauleyma requested changes

2022-12-14 02:08 UTC, mccauleyma commented on shepherd_bms/src/compute.cpp
> +    chargerMsg.cfg.chargerCurrent = (currentToSet - 3200) * 10; //todo double check order of ops
This seems backwards

2022-12-15 19:05 UTC, merged